image: node:18.14.0

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: https://docs.gitlab.com/ee/ci/services/index.html
# services:
#  - mongodb:lastest
stages:
  - test

test_server:
  stage: test
  script:
    - npm install
    - npm run test
